# micrograd exercises

1. watch the [micrograd video](https://www.youtube.com/watch?v=VMj-3S1tku0) on YouTube
2. come back and complete these exercises to level up :)

## section 1: derivatives

In [1]:
# here is a mathematical expression that takes 3 inputs and produces one output
from math import sin, cos

def f(a, b, c):
  return -a**3 + sin(3*b) - 1.0/c + b**2.5 - a**0.5

print(f(2, 3, 4))

6.336362190988558


In [2]:
import math

In [3]:
# write the function df that returns the analytical gradient of f
# i.e. use your skills from calculus to take the derivative, then implement the formula
# if you do not calculus then feel free to ask wolframalpha, e.g.:
# https://www.wolframalpha.com/input?i=d%2Fda%28sin%283*a%29%29%29

def gradf(a, b, c):
  gradf_a = - 3 * a**2 - 0.5 * a ** -(0.5)
  gradf_b = 3* cos(3*b) + 2.5 * b ** 1.5
  gradf_c = 1/c**2
  return [gradf_a, gradf_b, gradf_c] # todo, return [df/da, df/db, df/dc]

# expected answer is the list of
ans = [-12.353553390593273, 10.25699027111255, 0.0625]
yours = gradf(2, 3, 4)
for dim in range(3):
  ok = 'OK' if abs(yours[dim] - ans[dim]) < 1e-5 else 'WRONG!'
  print(f"{ok} for dim {dim}: expected {ans[dim]}, yours returns {yours[dim]}")


OK for dim 0: expected -12.353553390593273, yours returns -12.353553390593273
OK for dim 1: expected 10.25699027111255, yours returns 10.25699027111255
OK for dim 2: expected 0.0625, yours returns 0.0625


In [4]:
# now estimate the gradient numerically without any calculus, using
# the approximation we used in the video.
# you should not call the function df from the last cell

# -----------
numerical_grad = [0, 0, 0] # TODO
h = 0.000001
numerical_grad[0] = (f((2+h), 3, 4) - f(2,3, 4))/h
numerical_grad[1] = (f(2, 3+h, 4) - f(2,3, 4))/h
numerical_grad[2] = (f(2, 3, 4+h) - f(2,3, 4))/h
# -----------

for dim in range(3):
  ok = 'OK' if abs(numerical_grad[dim] - ans[dim]) < 1e-5 else 'WRONG!'
  print(f"{ok} for dim {dim}: expected {ans[dim]}, yours returns {numerical_grad[dim]}")


OK for dim 0: expected -12.353553390593273, yours returns -12.353559348809995
OK for dim 1: expected 10.25699027111255, yours returns 10.256991666679482
OK for dim 2: expected 0.0625, yours returns 0.062499984743169534


In [5]:
# there is an alternative formula that provides a much better numerical
# approximation to the derivative of a function.
# learn about it here: https://en.wikipedia.org/wiki/Symmetric_derivative
# implement it. confirm that for the same step size h this version gives a
# better approximation.

# -----------
numerical_grad2 = [0, 0, 0] # TODO
h = 0.000001
numerical_grad2[0] = (f((2+h), 3, 4) - f((2-h),3, 4))/(2*h)
numerical_grad2[1] = (f(2, 3+h, 4) - f(2,3-h, 4))/(2*h)
numerical_grad2[2] = (f(2, 3, 4+h) - f(2,3, 4-h))/(2*h)
# -----------

for dim in range(3):
  ok = 'OK' if abs(numerical_grad2[dim] - ans[dim]) < 1e-5 else 'WRONG!'
  print(f"{ok} for dim {dim}: expected {ans[dim]}, yours returns {numerical_grad2[dim]}")


OK for dim 0: expected -12.353553390593273, yours returns -12.353553391353245
OK for dim 1: expected 10.25699027111255, yours returns 10.25699027401572
OK for dim 2: expected 0.0625, yours returns 0.06250000028629188


## section 2: support for softmax

In [6]:
# Value class starter code, with many functions taken out
from math import exp, log

class Value:

  def __init__(self, data, _children=(), _op='', label=''):
    self.data = data
    self.grad = 0.0
    self._backward = lambda: None
    self._prev = set(_children)
    self._op = _op
    self.label = label

  def __repr__(self):
    return f"Value(data={self.data})"

  def __add__(self, other): # exactly as in the video
    other = other if isinstance(other, Value) else Value(other)
    out = Value(self.data + other.data, (self, other), '+')

    def _backward():
      self.grad += 1.0 * out.grad
      other.grad += 1.0 * out.grad
    out._backward = _backward

    return out
      
  def __radd__(self, other):
      return self + other

  def __mul__(self, other):
      other = other if isinstance(other, Value) else Value(other)
      out = Value(self.data * other.data, (self, other), '*')
      def _backward():
          self.grad += other.data * out.grad
          other.grad += self.data * out.grad

      out._backward = _backward
      return out
  # def __mul__(self, other):
  #   other = other if isinstance(other, Value) else Value(other)
  #   out = Value(self.data * other.data, (self, other), '*')

  #   def _backward():
  #       self.grad += other.data * out.grad
  #       other.grad += self.data * out.grad

  #   out._backward = _backward
  #   return out
      
  def exp(self):
    out = Value(exp(self.data), (self, ), 'exp')

    def _backward():
      self.grad += out.grad * out.data
    out._backward = _backward

    return out

  def log(self):
    out = Value(log(self.data), (self, ), 'log')
    def _backward():
      self.grad += (1/self.data)* out.grad
    out._backward = _backward
    return out

  def __truediv__(self, other):
      return self * other ** -1

  def __pow__(self, other):
    assert isinstance(other, (int, float)), "Only supports int and float"
    out = Value(self.data**other, (self, ), f'**(other)')

    def _backward():
        self.grad += other * (self.data ** (other-1)) * out.grad
    out._backward = _backward
    return out
  def __neg__(self):
    return self * -1
        
  # ------
  # re-implement all the other functions needed for the exercises below
  # your code here
  # TODO
  # ------

  def backward(self): # exactly as in video
    topo = []
    visited = set()
    def build_topo(v):
      if v not in visited:
        visited.add(v)
        for child in v._prev:
          build_topo(child)
        topo.append(v)
    build_topo(self)

    self.grad = 1.0
    for node in reversed(topo):
      node._backward()

In [7]:
# Add new operations for accommodate tanh calculation 

class Value:
    
    def __init__(self, data, _children=(), _op='', label=''):
        self.data = data
        self._prev = set(_children)
        self._backward = lambda : None
        self._op = _op
        self.label = label
        self.grad = 0
    
    def __repr__(self):
        return "Value(data={})".format(self.data)
    
    def __add__(self, other):
        other = other if isinstance(other, Value) else Value(other)
        out = Value(self.data + other.data, (self, other), '+')

        def _backward():
            self.grad += 1.0 * out.grad
            other.grad += 1.0 * out.grad

        out._backward = _backward
        return out
    
    def __mul__(self, other):
        other = other if isinstance(other, Value) else Value(other)
        out = Value(self.data * other.data, (self, other), '*')

        def _backward():
            self.grad += other.data * out.grad
            other.grad += self.data * out.grad

        out._backward = _backward
        return out
      

    def __radd__(self, other):
        return self + other

    def __rmul__(self, other):
        return self * other

    def __truediv__(self, other):
        return self * other ** -1

    def __pow__(self, other):
        assert isinstance(other, (int, float)), "Only supports int and float"
        out = Value(self.data**other, (self, ), f'**(other)')

        def _backward():
            self.grad = other * (self.data ** (other-1)) * out.grad
        out._backward = _backward
        return out

    def __neg__(self):
        return self * -1

    def __sub__(self, other):
        return self + (-other)
        

    def tanh(self):
        n = self.data
        t = (math.exp(2*n) - 1)/(math.exp(2*n) + 1)
        out = Value(t , (self, ), "tanh")

        def _backward():
            self.grad += (1-t**2) * out.grad
            
        out._backward = _backward
        return out

    def exp(self):
        n = self.data
        out = Value(math.exp(n), (self, ), "exp")

        def _backward():
            self.grad =out.data * out.grad
        out._backward = _backward
        return out
        
    def log(self):
        n = self.data
        out = Value(math.log(n), (self, ), "log")
    
        def _backward():
            self.grad += (1/n) * out.grad
        out._backward = _backward
        return out

    

    def backward(self):
        
        topo = []
        visited = set()
        def build_topo(v):
            if v not in visited:
                visited.add(v)
                for child in v._prev:
                    build_topo(child)
                topo.append(v)
        build_topo(self)

        self.grad = 1.0
        for node in reversed(topo):
            node._backward()

In [8]:
a = Value(2)
b = Value(20)
c = b/a
# exp(2.0)
d = c.log()
d.backward()
print(d, d.grad)
print(c, c.grad)
print(b, b.grad)
print(a, a.grad)

Value(data=2.302585092994046) 1.0
Value(data=10.0) 0.1
Value(data=20) 0.05
Value(data=2) -0.5


In [9]:
# without referencing our code/video __too__ much, make this cell work
# you'll have to implement (in some cases re-implemented) a number of functions
# of the Value object, similar to what we've seen in the video.
# instead of the squared error loss this implements the negative log likelihood
# loss, which is very often used in classification.

# this is the softmax function
# https://en.wikipedia.org/wiki/Softmax_function
def softmax(logits):
  counts = [logit.exp() for logit in logits]
  denominator = sum(counts)
  out = [c / denominator for c in counts]
  return out

# this is the negative log likelihood loss function, pervasive in classification
logits = [Value(0.0), Value(3.0), Value(-2.0), Value(1.0)]
probs = softmax(logits)
loss = -probs[3].log() # dim 3 acts as the label for this input example
loss.backward()
print(loss.data)

ans = [0.041772570515350445, 0.8390245074625319, 0.005653302662216329, -0.8864503806400986]
for dim in range(4):
  ok = 'OK' if abs(logits[dim].grad - ans[dim]) < 1e-5 else 'WRONG!'
  print(f"{ok} for dim {dim}: expected {ans[dim]}, yours returns {logits[dim].grad}")


2.1755153626167147
OK for dim 0: expected 0.041772570515350445, yours returns 0.041772570515350445
OK for dim 1: expected 0.8390245074625319, yours returns 0.8390245074625319
OK for dim 2: expected 0.005653302662216329, yours returns 0.005653302662216329
OK for dim 3: expected -0.8864503806400986, yours returns -0.8864503806400986


In [10]:
# verify the gradient using the torch library
# torch should give you the exact same gradient
import torch

In [11]:
a = torch.tensor([0.0]); a.requires_grad = True
b = torch.tensor([3.0]); b.requires_grad = True
c = torch.tensor([-2.0]); c.requires_grad = True
d = torch.tensor([1.0]); d.requires_grad = True
logits = [a, b, c, d]
probs = softmax(logits)
loss = -probs[3].log()
loss.backward()
print(loss.data)
ans = [0.041772570515350445, 0.8390245074625319, 0.005653302662216329, -0.8864503806400986]
for dim in range(4):
  ok = 'OK' if abs(logits[dim].grad - ans[dim]) < 1e-5 else 'WRONG!'
  print(f"{ok} for dim {dim}: expected {ans[dim]}, yours returns {logits[dim].grad}")

tensor([2.1755])
OK for dim 0: expected 0.041772570515350445, yours returns tensor([0.0418])
OK for dim 1: expected 0.8390245074625319, yours returns tensor([0.8390])
OK for dim 2: expected 0.005653302662216329, yours returns tensor([0.0057])
OK for dim 3: expected -0.8864503806400986, yours returns tensor([-0.8865])


In [12]:
a = torch.tensor([2.0]); a.requires_grad = True
b = torch.tensor([20.0]); b.requires_grad = True
c = b/a;
# exp(2.0)
d = c.log();
d.backward()
print(d, d.grad)
print(c, c.grad)
print(b, b.grad)
print(a, a.grad)

tensor([2.3026], grad_fn=<LogBackward0>) None
tensor([10.], grad_fn=<DivBackward0>) None
tensor([20.], requires_grad=True) tensor([0.0500])
tensor([2.], requires_grad=True) tensor([-0.5000])


/tmp/ipykernel_10755/76021403.py:7: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(d, d.grad)
/tmp/ipykernel_10755/76021403.py:8: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for mor

In [13]:
a = Value(2)
b = Value(20)
c = b/a
# exp(2.0)
d = c.log()
d.backward()
print(d, d.grad)
print(c, c.grad)
print(b, b.grad)
print(a, a.grad)

Value(data=2.302585092994046) 1.0
Value(data=10.0) 0.1
Value(data=20) 0.05
Value(data=2) -0.5
